baseURL = "https://comtipo.com/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Comtipo"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "Comtipo - Livraria e Importadora"
  description = "Soluções Digitais e Comércio Inteligente"
  author = "Comtipo"
  
  # Visual e Favicon
  defaultTheme = "light"
  disableThemeToggle = true
  ShowShareButtons = false
  ShowReadingTime = false
  displayFullLangName = true
  
  # Ocultar Metadados (Datas/Autor)
  hidemeta = true
  hideSummary = true
  
  # Rodapé
  copyright = "© 2026 Comtipo. Todos os direitos reservados."

  [params.assets]
    favicon = "favicon.ico" # O arquivo deve estar em static/favicon.ico
    disableHLJS = true

  [params.profileMode]
    enabled = true
    title = "Comtipo"
    subtitle = "Inovação e Comércio"
    imageUrl = ""
    imageTitle = "Logo Comtipo"
    buttons = [
      { name = "Nossos Produtos", url = "/produtos" },
      { name = "Entre em Contato", url = "/contato" }
    ]

  [params.label]
    text = "Comtipo"
    icon = "images/logo-comtipo.png"
    iconHeight = 35

# Menus
[[menu.main]]
  identifier = "produtos"
  name = "Catálogo"
  url = "/produtos/"
  weight = 10

[[menu.main]]
  identifier = "sobre"
  name = "A Marca"
  url = "/sobre/"
  weight = 20

[[menu.main]]
  identifier = "contato"
  name = "Contato"
  url = "/contato/"
  weight = 30